# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Model/'
            - '../src/Enum/'
            - '../src/DTO/'
            - '../src/Kernel.php'

    App\Service\Ping\PingRunnerInterface: '@App\Service\Ping\SystemPingRunner'
